// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: "2025-05-15",
  ssr: false,
  devtools: { enabled: true },

  modules: [
    "@nuxt/content",
    "@nuxt/eslint",
    "@nuxt/fonts",
    "@nuxt/scripts",
    "@nuxt/test-utils",
    "@nuxt/image",
    "vuetify-nuxt-module",
  ],
  vuetify: {
    vuetifyOptions: {
      components: [
        "VAlert",
        "VAlertTitle",
        "VApp",
        "VAppBar",
        "VAppBarNavIcon",
        "VAppBarTitle",
        "VAutocomplete",
        "VAvatar",
        "VBadge",
        "VBanner",
        "VBannerActions",
        "VBannerText",
        "VBottomNavigation",
        "VBottomSheet",
        "VBreadcrumbs",
        "VBreadcrumbsDivider",
        "VBreadcrumbsItem",
        "VBtn",
        "VBtnGroup",
        "VBtnToggle",

        "VCard",
        "VCardActions",
        "VCardItem",
        "VCardSubtitle",
        "VCardText",
        "VCardTitle",
        "VCarousel",
        "VCarouselItem",
        "VCheckbox",
        "VCheckboxBtn",
        "VChip",
        "VChipGroup",
        "VClassIcon",
        "VCode",
        "VCol",
        "VColorPicker",
        "VCombobox",
        "VComponentIcon",
        "VConfirmEdit",
        "VContainer",
        "VCounter",
        "VDataIterator",
        "VDataTable",
        "VDataTableFooter",
        "VDataTableHeaders",
        "VDataTableRow",
        "VDataTableRows",
        "VDataTableServer",
        "VDataTableVirtual",
        "VDatePicker",
        "VDatePickerControls",
        "VDatePickerHeader",
        "VDatePickerMonth",
        "VDatePickerMonths",
        "VDatePickerYears",
        "VDefaultsProvider",
        "VDialog",
        "VDialogBottomTransition",
        "VDialogTopTransition",
        "VDialogTransition",
        "VDivider",
        "VEmptyState",
        "VExpandTransition",
        "VExpandXTransition",
        "VExpansionPanel",
        "VExpansionPanels",
        "VExpansionPanelText",
        "VExpansionPanelTitle",
        "VFab",
        "VFabTransition",
        "VFadeTransition",
        "VField",
        "VFieldLabel",
        "VFileInput",
        "VFooter",
        "VForm",
        "VHover",
        "VIcon",
        "VImg",
        "VInfiniteScroll",
        "VInput",
        "VItem",
        "VItemGroup",
        "VKbd",
        "VLabel",
        "VLayout",
        "VLayoutItem",
        "VLazy",
        "VLigatureIcon",
        "VList",
        "VListGroup",
        "VListImg",
        "VListItem",
        "VListItemAction",
        "VListItemMedia",
        "VListItemSubtitle",
        "VListItemTitle",
        "VListSubheader",
        "VLocaleProvider",
        "VMain",
        "VMenu",
        "VMessages",
        "VNavigationDrawer",
        "VNoSsr",
        "VNumberInput",
        "VOtpInput",
        "VOverlay",
        "VPagination",
        "VParallax",

        "VProgressCircular",
        "VProgressLinear",

        "VRadio",
        "VRadioGroup",
        "VRangeSlider",
        "VRating",
        "VResponsive",
        "VRow",
        "VScaleTransition",
        "VScrollXReverseTransition",
        "VScrollXTransition",
        "VScrollYReverseTransition",
        "VScrollYTransition",
        "VSelect",
        "VSelectionControl",
        "VSelectionControlGroup",
        "VSheet",
        "VSkeletonLoader",
        "VSlideGroup",
        "VSlideGroupItem",
        "VSlider",
        "VSlideXReverseTransition",
        "VSlideXTransition",
        "VSlideYReverseTransition",
        "VSlideYTransition",
        "VSnackbar",
        "VSnackbarQueue",
        "VSpacer",
        "VSparkline",
        "VSpeedDial",
        "VStepper",
        "VStepperActions",
        "VStepperHeader",
        "VStepperItem",

        "VStepperWindow",
        "VStepperWindowItem",
        "VSvgIcon",
        "VSwitch",
        "VSystemBar",
        "VTab",
        "VTable",
        "VTabs",
        "VTabsWindow",
        "VTabsWindowItem",
        "VTextarea",
        "VTextField",
        "VThemeProvider",
        "VTimeline",
        "VTimelineItem",

        "VToolbar",
        "VToolbarItems",
        "VToolbarTitle",
        "VTooltip",

        "VValidation",
        "VVirtualScroll",
        "VWindow",
        "VWindowItem",

        // "VDateInput",
        // "VCalendar",
        // "VCalendarDay",
        // "VCalendarHeader",
        // "VCalendarInterval",
        // "VCalendarIntervalEvent",
        // "VCalendarMonthDay",
        // "VPicker",
        // "VPickerTitle",
        // "VPullToRefresh",
        // "VStepperVertical",
        // "VStepperVerticalActions",
        // "VStepperVerticalItem",
        // "VTimePicker",
        // "VTimePickerClock",
        // "VTimePickerControls",
        // "VTreeview",
        // "VTreeviewGroup",
        // "VTreeviewItem",
      ],
      labComponents: true,
    },
  },
});
